Adding resistance input

diff --git a/coil-calc b/coil-calc
--- a/coil-calc
+++ b/coil-calc
@@ -9,15 +9,16 @@ CSV="coils.csv"
 # numeric . numeric
 validateNumber ()
 {
-	if [ -n "$1" ]
+	if [ -z "$1" ]
+	then 
+		return 0
+	elif ! [[ "$1" =~ ^[0-9]+$ ]] && ! [[ "$1" =~ ^[-+]?[0-9]+\.?[0-9]*$ ]] ; 
 	then
-		if ! [[ "$1" =~ ^[0-9]+$ ]] && ! [[ "$1" =~ ^[-+]?[0-9]+\.?[0-9]*$ ]] ; 
-		then
-			echo -n "Error: '$1' is not a number"
-			return 0
-		fi
+		echo -n "Error: '$1' is not a number, "
+		return 0
+	else
+		return 1
 	fi
-	return 1
 }
 
 echo "Select a wire by entering it's corresponding number"
@@ -51,7 +52,7 @@ validateNumber $DIAMETER
 if [[ $? -eq 0 ]];
 then 
 	DIAMETER=3
-	echo ", setting the coil jig diameter to the default of 3"
+	echo "setting the coil jig diameter to the default of 3 mm"
 fi
 echo "The coil jig diameter is $DIAMETER mm"
 
@@ -65,6 +66,20 @@ validateNumber $LEAD
 if [[ $? -eq 0 ]];
 then 
 	LEAD=5
-	echo ", setting the lead length to the defult of 5"
+	echo "setting the lead length to the defult of 5 mm"
 fi
 echo "The lead length is $LEAD mm"
+
+# Get the desired resistance
+echo ""
+echo "What is the desired resistance of each coil (Default 1 ohm)?"
+read -r RESISTANCE
+
+# Check the input 
+validateNumber $RESISTANCE
+if [[ $? -eq 0 ]];
+then
+	RESISTANCE=1
+	echo "setting the resistance to the default of 1 ohm"
+fi
+echo "The resistnace is $RESISTANCE ohm"
